import { ILinkFunc } from "../fme/sidebar/data";
import {
  ActiveCourseList,
  ActiveHome,
  ActiveSettingsIcon,
  ActiveStcPageIcon,
  ActiveStudentList,
  ActiveSupportIcon,
  AllCoursesIcon,
  AllStudentTIcon,
  HomeIcon,
  SettingsIcon,
  StcPageIcon,
  SupportIcon,
} from "../icons/sidebar";

export const MDAPageLinks: ILinkFunc[] = [
  {
    href: "/mda",
    icon: <HomeIcon />,
    isSelected: true,
    id: "1",
    name: "Dashboard",
    activeState: <ActiveHome />,
  },
  {
    href: "/mda/all-students",
    icon: <AllStudentTIcon />,
    isSelected: false,
    id: "4",
    name: "All Students List",
    activeState: <ActiveStudentList />,
  },
  {
    href: "/mda/stcs",
    icon: <StcPageIcon />,
    isSelected: false,
    id: "3",
    name: "STCs",
    activeState: <ActiveStcPageIcon />,
  },
  {
    href: "/mda/course-list",
    icon: <AllCoursesIcon />,
    isSelected: false,
    id: "5",
    name: "Course List",
    activeState: <ActiveCourseList />,
  },
  {
    href: "/mda/settings",
    icon: <SettingsIcon />,
    isSelected: false,
    id: "6",
    name: "Settings",
    activeState: <ActiveSettingsIcon />,
  },
  {
    href: "/mda/support",
    icon: <SupportIcon />,
    isSelected: false,
    id: "7",
    name: "Support",
    activeState: <ActiveSupportIcon />,
  },
];


export const STCPageLinks: ILinkFunc[] = [
  {
    href: "/stc",
    icon: <HomeIcon />,
    isSelected: true,
    id: "1",
    name: "Dashboard",
    activeState: <ActiveHome />,
  },
  {
    href: "/stc/all-students",
    icon: <AllStudentTIcon />,
    isSelected: false,
    id: "4",
    name: "All Students List",
    activeState: <ActiveStudentList />,
  },
  {
    href: "/stc/course-list",
    icon: <AllCoursesIcon />,
    isSelected: false,
    id: "5",
    name: "Course List",
    activeState: <ActiveCourseList />,
  },
  {
    href: "/stc/settings",
    icon: <SettingsIcon />,
    isSelected: false,
    id: "6",
    name: "Settings",
    activeState: <ActiveSettingsIcon />,
  },
  {
    href: "/support",
    icon: <SupportIcon />,
    isSelected: false,
    id: "7",
    name: "Support",
    activeState: <ActiveSupportIcon />,
  },
];
