import { StcDataInterface } from "../(interface)/interface"
const StcData:StcDataInterface[]=[
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:"10",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"1",
},
    {
        name:"AGRICULTURAL SKILLS CENTRE, DAMARE",
        courses:"40",
        total_students:300,
        address:"30, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"2",
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:"10",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"3",
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:"1",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"4",
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:"1",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"5",
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:"1",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"6",
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:"1",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"7",
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:"1",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"8",
},
    {
        name:" OF WORKS AND HOUSING",
        courses:"1",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"9",
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:"1",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"10",
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:"1",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"11",
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:"1",
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        id:"12",
},
]

export {StcData}