import { StcDataInterface } from "../(interface)/interface"
const StcData:StcDataInterface[]=[
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:1,
},
    {
        name:"AGRICULTURAL SKILLS CENTRE, DAMARE",
        courses:4,
        total_students:300,
        address:"30, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:2,
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:3,
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:4,
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:5,
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:6,
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:7,
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:8,
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:9,
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:10,
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:11,
},
    {
        name:"FEDERAL MINISTRY OF WORKS AND HOUSING",
        courses:1,
        total_students:200,
        address:"1, Hervbert Way",
        state:"Lagos",
        status:"Active",
        index:12,
},
]

export {StcData}